//! Pixel patterns for the ancient map, transcribed from
//! `worldengine/drawing_functions.py`.
//!
//! Each entry is `(dy, dx, use_secondary_colour)`; the order matters because
//! later writes overwrite earlier ones.

pub(crate) const FOREST_PATTERN1: [(i64, i64, bool); 33] = [
    (-4, 0, false),
    (-3, 0, false),
    (-2, -1, false),
    (-2, 1, false),
    (-1, -1, false),
    (-1, 1, false),
    (0, -2, false),
    (0, 1, false),
    (0, 2, false),
    (1, -2, false),
    (1, 2, false),
    (2, -3, false),
    (2, -1, false),
    (2, 3, false),
    (3, -3, false),
    (3, -2, false),
    (3, -1, false),
    (3, 0, false),
    (3, 1, false),
    (3, 2, false),
    (3, 3, false),
    (4, 0, false),
    (-2, 0, true),
    (-1, 0, true),
    (0, -1, true),
    (0, 0, true),
    (1, -1, true),
    (1, 0, true),
    (1, 1, true),
    (2, -2, true),
    (2, 0, true),
    (2, 1, true),
    (2, 2, true),
];

pub(crate) const FOREST_PATTERN2: [(i64, i64, bool); 33] = [
    (-4, -1, false),
    (-4, 0, false),
    (-4, 1, false),
    (-3, -2, false),
    (-3, -1, false),
    (-3, 2, false),
    (-2, -2, false),
    (-2, 1, false),
    (-2, 2, false),
    (-1, -2, false),
    (-1, 2, false),
    (0, -2, false),
    (0, -1, false),
    (0, 2, false),
    (1, -2, false),
    (1, 1, false),
    (1, 2, false),
    (2, -1, false),
    (2, 0, false),
    (2, 1, false),
    (3, 0, false),
    (4, 0, false),
    (-3, 0, true),
    (-3, 1, true),
    (-2, -1, true),
    (-2, 0, true),
    (-1, -1, true),
    (-1, 0, true),
    (-1, 1, true),
    (0, 0, true),
    (0, 1, true),
    (1, -1, true),
    (1, 0, true),
];

/// The desert pattern uses a single colour.
pub(crate) const DESERT_PATTERN: [(i64, i64); 22] = [
    (-2, -1),
    (-2, 0),
    (-2, 1),
    (-2, 1),
    (-2, 2),
    (-1, -2),
    (-1, -1),
    (-1, 0),
    (-1, 4),
    (0, -4),
    (0, -3),
    (0, -2),
    (0, -1),
    (0, 1),
    (0, 2),
    (0, 6),
    (1, -5),
    (1, 0),
    (1, 7),
    (1, 8),
    (2, -8),
    (2, -7),
];
