//! Shared helpers for the ported test suites.
#![allow(dead_code)]

use std::path::PathBuf;

/// Load one of the reference-vector fixtures generated by `tools/gen_vectors.py`.
pub fn fixture(name: &str) -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read fixture {}: {e}", path.display()))
}

/// Parse a big-endian IEEE-754 hex string as written by `gen_vectors.py`.
pub fn f64_from_hex(s: &str) -> f64 {
    let bytes = u64::from_str_radix(s, 16).expect("bad f64 hex");
    f64::from_bits(bytes)
}

pub fn f32_from_hex(s: &str) -> f32 {
    let bytes = u32::from_str_radix(s, 16).expect("bad f32 hex");
    f32::from_bits(bytes)
}

/// Locate the `worldengine-data` fixtures repository, the same way the Python
/// tests do (a sibling checkout), with an environment override.
pub fn data_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("WORLDENGINE_DATA_DIR") {
        return PathBuf::from(dir);
    }
    let candidate = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("worldengine-data");
    assert!(
        candidate.is_dir(),
        "worldengine-data doesn't exist, please clone it before continuing \
         (git clone https://github.com/Mindwerks/worldengine-data.git next to this repo), \
         or set WORLDENGINE_DATA_DIR"
    );
    candidate
}

pub fn tests_data_dir() -> PathBuf {
    data_dir().join("tests").join("data")
}

pub fn tests_images_dir() -> PathBuf {
    data_dir().join("tests").join("images")
}
